# Generated by Django 5.0.2 on 2024-02-17 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_rename_conservation_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='conservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.conversation'),
        ),
    ]
