# Generated by Django 5.0.2 on 2024-02-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_rename_created_at_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='conservation',
            new_name='conversation',
        ),
    ]
